### ISSUE TITLE
Preparing files to be processed

### ISSUE THREAD

**Issue by ayaylali** [writecrow/ciabatta#7]
Hi,

I have been reviewing the wiki for my own use and I have noticed a repetitive statement in this particular section, starting with "You may have files in a variety of formats...". This entire section is repeated in the same section. You might want to remove it. 

https://github.com/writecrow/ciabatta/wiki/Corpus-Text-Processor

Thank you.

**Comment by markfullmer** [comment]
Thanks, @ayaylali . I've removed the redundant text.
